apiVersion: v1
kind: Namespace
metadata:
  name: bi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-data-pvc
  namespace: bi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# K3s 기본 스토리지 클래스 사용 (로컬 패스)
# storageClassName: local-path 
