apiVersion: apps/v1
kind: Deployment
metadata:
  name: piston
  labels:
    app: piston
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piston
  template:
    metadata:
      labels:
        app: piston
    spec:
      containers:
        - name: piston
          image: ghcr.io/engineer-man/piston:latest
          ports:
            - containerPort: 2000
          securityContext:
            privileged: true
          volumeMounts:
            - name: piston-packages
              mountPath: /piston/packages
      volumes:
        - name: piston-packages
          persistentVolumeClaim:
            claimName: piston-packages-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piston-packages-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
